### ISSUE TITLE
ReviewRequestProcessor- queryExistingInst method

### ISSUE THREAD

**Issue by syou1707** [CSC207-UofT/course-project-bug-makers#54]
I just wanted to double check but does the `queryExistingInst` method in the `ReviewRequestProcessor` want an ArrayList of all the existing instructors' names for a given course? (Since there are different instructors for different sections of a course, I assumed we wanted to return the list of all instructors for a given course). I ended up using the `CourseDAO` to do this (while everything else used `ReviewDAO`), so I'm not sure if this is right:
<img width="699" alt="Screen Shot 2021-11-12 at 11 04 59 AM" src="https://user-images.githubusercontent.com/90635127/141497541-2f3fc4f2-264a-47f5-8198-d7d9211f8637.png">

**Comment by Kuan-Pang** [comment]
This `queryExistingInst` is intended to return the list of instructors that are already in the database. The user can check the result of `queryExistingInst` and see if his instructor is in the database, if instructor is in the db, we dont need to create another `InstReview` entity and just add the user's review under that `InstReview`. But if the instructor is not in the db, we will want to create a new `InstReview` entity and then add user's review.

**Comment by syou1707** [comment]
Ohh I see ok. Right now theres no method in the `ReviewDaoImpl` that finds the list of existing instructors so should I add one to that class? (Like for the method `queryExistingCourse`  in `ReviewRequestProcessor`, I used `queryExistingCourse` from the `ReviewDaoImpl`, but there is no method in `ReviewDaoImpl` that queries the instructors right now.) 
<img width="490" alt="Screen Shot 2021-11-12 at 11 20 57 AM" src="https://user-images.githubusercontent.com/90635127/141499594-6d7edcc9-f0af-44f5-8261-999d1b2b011e.png">

**Comment by Kuan-Pang** [comment]
That would work but there is a method `getInstList()` in the `CourseReview` entity, its easier to query a `CourseReview` entity and do the `getInstList()`, it will return the instructor list under a `CourseReview`.

This follows clean structure cause both daoImpl and ReviewRequestProcessor are on the Use Case level, they can interact with the entity.

**Comment by syou1707** [comment]
Oh ok got it thank you!
