### ISSUE TITLE
Implementation of planCourse

### ISSUE THREAD

**Issue by chengk68** [CSC207-UofT/course-project-bug-makers#61]
Currently, the new implementation of planCourse involves using a helper function (is that allowed?) that creates all possible schedules, then chooses the first of the list. 
One bit of functionality we can very easily add is to allow the user to cycle through the possible schedules, and maybe even search for specific schedules. 
The biggest issue with this is that I have struggled with implementing the wishlist. I feel like there may be an easy solution, but I haven't been able to figure it out. We should discuss this in the future, but for now I have removed the wishlist implementation.

**Comment by Kuan-Pang** [comment]
helper function is allowed, npnp, we can talk about it today. 👍
