### ISSUE TITLE
Errors in `ReviewRequestProcessor`

### ISSUE THREAD

**Issue by Lola-W** [CSC207-UofT/course-project-bug-makers#70]
The outcome of `queryExistingInst()` and `queryUsername()` in `ReviewRequestProcessor` are not as expected.
![image](https://user-images.githubusercontent.com/79666594/141695325-bece3301-d021-4f2a-9fa7-f5af53c3c19b.png)

**Comment by syou1707** [comment]
Hii do you know the expected outcomes for both of these methods so I can check to see if I can fix it?

**Comment by Lola-W** [comment]
> Hii do you know the expected outcomes for both of these methods so I can check to see if I can fix it?

No worries! I fixed it in PR #71!
